version: "3"
services:
  zookeeper:
    image: debezium/zookeeper:1.6
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:1.6
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - "kafka-data-prod:/kafka/data"
    restart: always

  database:
    image: debezium/postgres:11
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=SQ6EPGsH2jbRKASA
      - POSTGRES_DB=codimd
    volumes:
      - "postgres-data-prod:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5432:5432"

  connect:
    image: debezium/connect:1.6
    ports:
     - 8083:8083

    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

  kowl: 
    image: quay.io/cloudhut/kowl:master
    ports:
      - 5000:8080
    environment:
      - KAFKA_BROKERS=kafka:9092
  
  
  codimd:
    # you can use image or custom build below,
    # if you need CJK character with exported PDF files,
    # please change the image tag with `cjk` postfix version
    #image: nabo.codimd.dev/hackmdio/hackmd:2.1.0
    # image: nabo.codimd.dev/hackmdio/hackmd:2.1.0-cjk
    build:
       context: ..
       dockerfile : ./deployments/Dockerfile 
       args:
        RUNTIME: hackmdio/runtime:node-10-0baafb79
        BUILDPACK: hackmdio/buildpack:node-10-0baafb79
    environment:
      - CMD_DB_URL=postgres://codimd:SQ6EPGsH2jbRKASA@database/codimd
      - CMD_USECDN=false
      - CMD_DOMAIN=codimd.ludentes.ru
      - CMD_URL_ADDPORT=443
      - CMD_PROTOCOL_USESSL=true
      - CMD_GITLAB_BASEURL=https://gitlab.ludentes.ru
      - CMD_GITLAB_CLIENTID=a1658156c91a5779dd5796c0ee48bd99a5b2194ffb3c75806bafc7df13df280b
      - CMD_GITLAB_CLIENTSECRET=1935443ab4d5036cf06974a5cd87675c8a5d9b49122ae6c69bc7b5a9512bfc4d
      - CMD_IMAGE_UPLOAD_TYPE=s3
      - CMD_S3_ACCESS_KEY_ID=AKIAVFX5MFLDKJKBG4BQ
      - CMD_S3_SECRET_ACCESS_KEY=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
      - CMD_S3_REGION=eu-central-1
      - CMD_S3_BUCKET=codemd 
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always

  pgbackups3:
    build:
       context: ../backup
       dockerfile: ./Dockerfile 
    links:
      - database
    environment:
      SCHEDULE: '@daily'
      S3_REGION: eu-central-1
      S3_ACCESS_KEY_ID: AKIAVFX5MFLDKJKBG4BQ
      S3_SECRET_ACCESS_KEY: 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
      S3_BUCKET: codemdbackup
      S3_PREFIX: backup
      POSTGRES_HOST: database
      POSTGRES_DATABASE: codimd
      POSTGRES_USER: codimd
      POSTGRES_PASSWORD: SQ6EPGsH2jbRKASA
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'


volumes:
  postgres-data-prod: {}
  kafka-data-prod: {}

  upload-data: {} 
